name: Deploy web app

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Install deps
      run: pip install -r requirements.txt

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Launch app
      run: |
        poe app